DROP DATABASE IF EXISTS notes;
CREATE DATABASE notes;
USE notes;

CREATE TABLE user (
	id INT(11) NOT NULL AUTO_INCREMENT,
	firstName VARCHAR(50) NOT NULL,
	lastName VARCHAR(50) NOT NULL,
	patronymic VARCHAR(50),
	login VARCHAR(50) NOT NULL UNIQUE,
	password VARCHAR(50) NOT NULL,
	userType ENUM('ADMIN', 'USER') DEFAULT 'USER',
	deleted BOOL DEFAULT FALSE,
    timeRegistered DATETIME NOT NULL,
	PRIMARY KEY (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE session (
	id INT(11) NOT NULL AUTO_INCREMENT,
	sessionId TINYTEXT NOT NULL,
    timeLogin DATETIME NOT NULL,
    userId INT(11) NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (userId) REFERENCES user (id)  ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;
    
    
CREATE TABLE following (
    id INT(11) NOT NULL AUTO_INCREMENT,
	userId INT(11) NOT NULL,
	followingId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
	FOREIGN KEY (followingId) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE `ignore` (
    id INT(11) NOT NULL AUTO_INCREMENT,
	userId INT(11) NOT NULL,
	ignoredId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (userId) REFERENCES user (id) ON DELETE CASCADE,
    FOREIGN KEY (ignoredId) REFERENCES user (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE section (
    id INT(11) NOT NULL AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL UNIQUE,
	ownerId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (ownerId) REFERENCES user (id)
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE note (
    id INT(11) NOT NULL AUTO_INCREMENT,
	subject VARCHAR(50) NOT NULL,
	rating DECIMAL(5, 4) DEFAULT 0,
	numberOfRatings INT(11) DEFAULT 0,
    timeCreated DATETIME NOT NULL,
	ownerId INT(11) NOT NULL,
	sectionId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (ownerId) REFERENCES user (id),
	FOREIGN KEY (sectionId) REFERENCES section (id)  ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE revision (
    id INT(11) NOT NULL AUTO_INCREMENT,
	body MEDIUMTEXT NOT NULL,
	noteId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (noteId) REFERENCES note (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;

CREATE TABLE comment (
    id INT(11) NOT NULL AUTO_INCREMENT,
	body VARCHAR(200) NOT NULL,
    timeCreated DATETIME NOT NULL,
	ownerId INT(11) NOT NULL,
	revisionId INT(11) NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (ownerId) REFERENCES user (id),
	FOREIGN KEY (revisionId) REFERENCES revision (id) ON DELETE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=utf8;
